apiVersion: v1
kind: Pod
metadata:
  name: tf-gpu-test
spec:
  containers:
  - name: tf-container
    image: tensorflow/tensorflow:latest-gpu
    command: ["python"]
    args: ["-c", "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"]
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    node-role.kubernetes.io/worker: "worker"