# kind 클러스터 설정 파일
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# 네트워킹 설정
networking:
  apiServerAddress: "0.0.0.0"  # API 서버가 모든 인터페이스에서 리스닝
  # apiServerPort: 6443  # API 서버 포트

# 노드 설정
nodes:
# 컨트롤 플레인 (마스터) 노드
- role: control-plane
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 6443  # Kubernetes API 서버
    hostPort: 6443
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 80  # HTTP 트래픽 (Ingress)
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443  # HTTPS 트래픽 (Ingress)
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"  # Ingress 준비 레이블 추가

# 워커 노드
- role: worker
  image: kindest/node:v1.26.15
  extraPortMappings:
  - containerPort: 30000  # NodePort 서비스 범위 시작
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 31000  # NodePort 서비스 추가 포트 예시
    hostPort: 31000
    listenAddress: "0.0.0.0"
    protocol: TCP