# apiVersion: v1
# kind: Pod
# metadata:
#   name: worker-gpu-test
# spec:
#   containers:
#   - name: cuda-container
#     image: nvidia/cuda:11.6.2-base-ubuntu20.04
#     command: ["nvidia-smi"]
#     resources:
#       limits:
#         nvidia.com/gpu: 1
#   nodeSelector:
#     kubernetes.io/hostname: jmlim-cluster-m02

---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: gpu-test-pod
# spec:
#   containers:
#   - name: gpu-test-container
#     image: nvidia/cuda:12.6.0-base-ubuntu22.04
#     command: ["nvidia-smi"]
#     resources:
#       limits:
#         nvidia.com/gpu: 1
#     securityContext:
#       privileged: true
#   nodeSelector:
#     nvidia.com/gpu: "true"
#   tolerations:
#   - key: nvidia.com/gpu
#     operator: Exists
#     effect: NoSchedule
#   restartPolicy: Never
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: cuda-vector-add
# spec:
#   restartPolicy: OnFailure
#   containers:
#     - name: cuda-vector-add
#       image: "k8s.gcr.io/cuda-vector-add:v0.1"
#       resources:
#         limits:
#           nvidia.com/gpu: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-gpu-test
spec:
  containers:
  - name: nvidia-gpu-test
    image: nvidia/cuda:12.6.0-base-ubuntu22.04
    command: ["nvidia-smi"]
  restartPolicy: Never